#%RAML 1.0 Library
usage: Contains types of aws-sapi
types:
  upload-s3-document-request-payload:
    type: object
    properties:
      bucketName:
        type: string
        required: true
        example: "uho-covid-docs"
      folderPath: 
        type: string
        required: true
        example: "identity"
      fileName: 
        type: string
        required: true
        example: "35653.png"
      document: 
        type: string
        required: true
        example: "iVBORw0KGgoAAAANSUhEUgAAAOIAAACRCAYAAADepmS4AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjw"
  upload-s3-document-response-payload:
    type: object
    properties:
          code:
            type: integer
            description: Document uploaded successfully
            required: true 
          message:
            description: Success
            type: string
            required: true
          description:
            description: A human readable, comprehensive explanation of the occurred exception
            type: string
            required: false
          dateTime:
            description: The date-time stamp of the occurred error
            type: datetime
            required: true
          transactionId:
            description: Internal identifier of the transaction that failed
            type: string
            required: true
